spring.application.name=restaurante-api
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/american_bites
spring.datasource.username=postgres
spring.datasource.password=Jdvg0326
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- MongoDB (persistencia NoSQL: log de eventos de pedidos) ---
# Local:
spring.data.mongodb.uri=mongodb://localhost:27017/american_bites
# MongoDB Atlas (reemplaza usuario, password y cluster):
# spring.data.mongodb.uri=mongodb+srv://USUARIO:PASSWORD@CLUSTER.mongodb.net/american_bites?retryWrites=true&w=majority

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
