@startuml
title Modelo Entidad-Relacion (relacional) - American Bites
hide circle
skinparam shadowing false

entity "MESAS" as mesas {
  * id : BIGINT [PK]
  --
  * numero : INTEGER [UNIQUE]
  * capacidad : INTEGER
  * estado : VARCHAR (DISPONIBLE/OCUPADA/RESERVADA)
  * cuenta_abierta : BOOLEAN
}

entity "PLATOS" as platos {
  * id : BIGINT [PK]
  --
  * nombre : VARCHAR(100) [UNIQUE]
  * precio : DOUBLE
  * categoria : VARCHAR
  * disponible : BOOLEAN
}

entity "PEDIDOS" as pedidos {
  * id : UUID [PK]
  --
  * id_mesa : BIGINT [FK -> MESAS]
  * estado : VARCHAR (RECIBIDO/EN_PREPARACION/LISTO/ENTREGADO/CANCELADO)
  * timestamp : TIMESTAMP
}

entity "ITEMS_PEDIDO" as items {
  * id : BIGINT [PK]
  --
  * pedido_id : UUID [FK -> PEDIDOS]
  * id_plato : BIGINT [referencia logica -> PLATOS]
  * nombre_plato : VARCHAR
  * precio_congelado : DOUBLE
  * cantidad : INTEGER
}

entity "CUENTAS" as cuentas {
  * id : BIGINT [PK]
  --
  * id_mesa : BIGINT [FK -> MESAS]
  * total : DOUBLE
  * estado : VARCHAR (ABIERTA/EN_PAGO/CERRADA)
  * fecha_apertura : TIMESTAMP
}

entity "RESERVAS" as reservas {
  * id : UUID [PK]
  --
  * id_mesa : BIGINT [FK -> MESAS]
  * cliente : VARCHAR
  * fecha_hora : TIMESTAMP
  * comensales : INTEGER
  * cancelada : BOOLEAN
}

mesas ||--o{ pedidos : "1:N"
mesas ||--o{ cuentas : "1:N"
mesas ||--o{ reservas : "1:N"
pedidos ||--|{ items : "1:N"
platos ||..o{ items : "referencia logica"
@enduml
